# Generated by Django 5.2.1 on 2026-02-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_admin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super Admin')], default='admin', help_text='The administrative level of the user.', max_length=20),
        ),
    ]
