# Generated by Django 5.2.1 on 2026-02-08 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(help_text='Short name for the client', max_length=100, unique=True)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('system_name', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.URLField(blank=True)),
                ('system_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('system_url', models.URLField(blank=True)),
                ('email_links_choicee', models.CharField(blank=True, choices=[('system IP', 'System IP'), ('system URL', 'System URL')], default='System IP', max_length=100)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_notified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(help_text="e.g., 'Value Change', 'State Transition'", max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=50)),
                ('name', models.CharField(help_text='Short name for the event', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Short name for the fault entry', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(help_text="The source of the log (e.g., 'System', 'Parameter_Update')", max_length=255)),
                ('message', models.TextField()),
                ('value', models.CharField(blank=True, help_text='Optional value associated with the log entry', max_length=255)),
                ('name', models.CharField(help_text='Short name for the log entry', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Notification', max_length=255)),
                ('link', models.CharField(default='/', max_length=500)),
                ('icon', models.CharField(default='info-circle', max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('type', models.CharField(help_text="e.g., 'critical', 'warning', 'info'.", max_length=100)),
                ('to', models.CharField(help_text='Short name for the notification entry', max_length=255)),
                ('status', models.CharField(help_text='Status of the notification', max_length=225)),
                ('push_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('auth', models.CharField(max_length=255)),
                ('p256dh', models.CharField(max_length=255)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(help_text="e.g., 'Daily Performance', 'Alarm Summary'", max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('file', models.FileField(upload_to='reports/')),
                ('name', models.CharField(help_text='Short name for the report entry', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('name', models.CharField(help_text='Short name for the trend entry', max_length=255)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MED', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.CharField(blank=True, help_text='Short name for who acknowledged the alarm', max_length=255)),
                ('acknowledged_time', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_cleared', models.BooleanField(default=False)),
                ('is_notified', models.BooleanField(default=False)),
                ('cleared_by', models.CharField(blank=True, help_text='Short name for who cleared the alarm', max_length=255)),
                ('deleted_by', models.CharField(blank=True, max_length=255)),
                ('cleared_time', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Short name for the alarm entry', max_length=255)),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='devices.point')),
            ],
        ),
    ]
