# Generated by Django 5.2.1 on 2026-02-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('AVR', 'AVR'), ('FIRE SYSTEM', 'Fire System'), ('ATS', 'ATS'), ('GENERATOR', 'Generator'), ('HVAC SYSTEM', 'HVAC System'), ('TRANSFORMER', 'Transformer'), ('UPS', 'UPS'), ('ENERGY METER', 'Energy Meter'), ('WATER METER', 'Water Meter'), ('LIFT', 'Lift'), ('LIGHTING CONTROL SYSTEM', 'Lighting Control System'), ('ACCESS CONTROL', 'Access Control'), ('SECURITY SYSTEM', 'Security System'), ('SURVEILLANCE SYSTEM', 'Surveillance System'), ('ENVIRONMENTAL SENSOR', 'Environmental Sensor'), ('UTILITY MANAGEMENT', 'Utility Management System'), ('GAS DETECTION SYSTEM', 'Gas Detection System'), ('PUMP CONTROLLER', 'Pump Controller'), ('VFD', 'VFD'), ('AUDIO VISUAL SYSTEM', 'Audio Visual System')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='protocol',
            field=models.CharField(blank=True, choices=[('Modbus', 'Modbus'), ('Bacnet', 'BACnet'), ('Mqtt', 'MQTT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='bit_size',
            field=models.PositiveSmallIntegerField(blank=True, default=16, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='direction',
            field=models.CharField(blank=True, choices=[('Input', 'Input'), ('Output', 'Output')], default='Input', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='error_status',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('FAULT', 'Hardware Fault'), ('COMM_ERROR', 'Communication Error'), ('RANGE_ERROR', 'Out of Range')], default='OK', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='frequency',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='gain',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='offset',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='range_max',
            field=models.FloatField(blank=True, default=20.0, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='range_min',
            field=models.FloatField(blank=True, default=4.0, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='read_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='scale_max',
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='scale_min',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='threshold_high',
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='threshold_low',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='write_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='data_type',
            field=models.CharField(blank=True, choices=[('Integer', 'Integer'), ('Float', 'Float'), ('Real', 'Real'), ('Boolean', 'Boolean')], default='Real', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='direction',
            field=models.CharField(blank=True, choices=[('Input', 'Input'), ('Output', 'Output')], default='Input', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='error_status',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('FAULT', 'Hardware Fault'), ('COMM_ERROR', 'Communication Error'), ('RANGE_ERROR', 'Out of Range')], default='OK', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='read_function_code',
            field=models.CharField(blank=True, choices=[('01', '01 - Read Coils'), ('02', '02 - Read Discrete Inputs'), ('03', '03 - Read Holding Registers'), ('04', '04 - Read Input Registers'), ('05', '05 - Write Single Coil'), ('06', '06 - Write Single Register'), ('15', '15 - Write Multiple Coils'), ('16', '16 - Write Multiple Registers')], default='04', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='signal_type',
            field=models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Analog', 'Analog'), ('Pulse', 'Pulse'), ('Multistate', 'Multistate')], default='Digital', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='write_function_code',
            field=models.CharField(blank=True, choices=[('01', '01 - Read Coils'), ('02', '02 - Read Discrete Inputs'), ('03', '03 - Read Holding Registers'), ('04', '04 - Read Input Registers'), ('05', '05 - Write Single Coil'), ('06', '06 - Write Single Register'), ('15', '15 - Write Multiple Coils'), ('16', '16 - Write Multiple Registers')], default='06', max_length=10, null=True),
        ),
    ]
