# Generated by Django 5.2.1 on 2026-02-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_device_type_alter_device_protocol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
