# Generated by Django 5.2.1 on 2026-02-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_point_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='protocol',
            field=models.CharField(blank=True, choices=[('ModbusTCP', 'Modbus TCP'), ('ModbusRTU', 'Modbus RTU'), ('BACnetIP', 'BACnet IP'), ('BACnetMSTP', 'BACnet MS/TP'), ('Mqtt', 'MQTT')], max_length=20, null=True),
        ),
    ]
