# Generated by Django 5.2.1 on 2026-02-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='bacnet_instance_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='bacnet_object_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Analog Input'), (1, 'Analog Output'), (2, 'Analog Value'), (3, 'Binary Input'), (4, 'Binary Output'), (5, 'Binary Value'), (13, 'Multi-state Input'), (14, 'Multi-state Output'), (19, 'Multi-state Value')], null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='bacnet_property_id',
            field=models.PositiveIntegerField(blank=True, default=85, null=True),
        ),
    ]
